#!/bin/sh

# Copyright (c) 1999 Sendmail, Inc. and its suppliers.
#	All rights reserved.
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the sendmail distribution.
#
#
#	$Id: Build,v 1.1.1.2 2001/01/15 20:52:08 millert Exp $

exec ../devtools/bin/Build $*
