#	$Id: IRIX.5.x,v 1.1.1.2 2001/01/15 20:51:58 millert Exp $
define(`confCC', `cc -mips2')
define(`confMAPDEF', `-DNDBM -DNIS')
define(`confENVDEF', `-DIRIX5')
define(`confLIBS', `-lmld -lmalloc')
define(`confMBINDIR', `/usr/lib')
define(`confSBINDIR', `/usr/etc')
define(`confUBINDIR', `/usr/bsd')
define(`confEBINDIR', `/usr/lib')
define(`confSBINGRP', `sys')
define(`confSTDIR', `/var')
define(`confINSTALL', `${BUILDBIN}/install.sh')
define(`confDEPEND_TYPE', `CC-M')
